<?php

/**
 * @file
 * Login Redirection Module hooks.
 */
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_login().
 */
function redirect_after_login_user_login($account) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  if (!in_array($current_route, ['user.reset', 'user.reset.login'])) {
    // We want to redirect user on login
    $current_user = \Drupal::currentUser();
    $username = $current_user->getRoles();
    $login_redirection = \Drupal::config('redirect_after_login.settings')
      ->get('login_redirection');
    if (isset($login_redirection[array_reverse($username)[0]])) {
      $response = new RedirectResponse(URL::fromUserInput($login_redirection[array_reverse($username)[0]])
          ->toString());
      $response->send();
    }
    else {
      $homeResponse = new RedirectResponse(URL::fromUserInput('/')->toString());
      $homeResponse->send();
    }
  }

  return;
}
