<?php

/**
 * @file
 * Contains myusf_subnav_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function myusf_subnav_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the myusf_subnav_block module.
    case 'help.page.myusf_subnav_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A dynamic block for displaying sub navigation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function myusf_subnav_block_theme() {
  return [
    'myusf_subnav_block' => [
      'render element' => 'children',
    ],
  ];
}
