<?php

namespace Drupal\usfb_address;

use Drupal\Core\Session\AccountInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Utility Service with common functions.
 *
 * @ingroup usfb_address
 */
class UsfbUtility {

  /**
   * The current user.
   *
   * @var \Drupal\Core\Session\AccountInterface
   */
  protected $currentUser;

  /**
   * Constructs a UsfbBannerApi object.
   *
   * @param \Drupal\Core\File\FileSystemInterface $file_system
   *   File system service.
   */
  public function __construct(AccountInterface $current_user) {
    $this->currentUser = $current_user;
  }

  /**
   * Clears the session flag and rediects the user to the post-login destination.
   */
  public function abort() {
    unset($_SESSION['usfb_address_check']);
    $url = Url::fromUri("user/{$this->currentUser->id()}/view")->toString();
    $response = new RedirectResponse($url);
    $response->send();
  }

  /**
   * Retrieve all the international phone data.
   */
  public function getPhoneCodes() {
    return array(
      'US' => array('value' => '1', 'text' => 'United States'),
      'DZ' => array('value' => '213', 'text' => 'Algeria'),
      'AD' => array('value' => '376', 'text' => 'Andorra'),
      'AO' => array('value' => '244', 'text' => 'Angola'),
      'AI' => array('value' => '1264', 'text' => 'Anguilla'),
      'AG' => array('value' => '1268', 'text' => 'Antigua &amp; Barbuda'),
      'AR' => array('value' => '54', 'text' => 'Argentina'),
      'AM' => array('value' => '374', 'text' => 'Armenia'),
      'AW' => array('value' => '297', 'text' => 'Aruba'),
      'AU' => array('value' => '61', 'text' => 'Australia'),
      'AT' => array('value' => '43', 'text' => 'Austria'),
      'AZ' => array('value' => '994', 'text' => 'Azerbaijan'),
      'BS' => array('value' => '1242', 'text' => 'Bahamas'),
      'BH' => array('value' => '973', 'text' => 'Bahrain'),
      'BD' => array('value' => '880', 'text' => 'Bangladesh'),
      'BB' => array('value' => '1246', 'text' => 'Barbados'),
      'BY' => array('value' => '375', 'text' => 'Belarus'),
      'BE' => array('value' => '32', 'text' => 'Belgium'),
      'BZ' => array('value' => '501', 'text' => 'Belize'),
      'BJ' => array('value' => '229', 'text' => 'Benin'),
      'BM' => array('value' => '1441', 'text' => 'Bermuda'),
      'BT' => array('value' => '975', 'text' => 'Bhutan'),
      'BO' => array('value' => '591', 'text' => 'Bolivia'),
      'BA' => array('value' => '387', 'text' => 'Bosnia Herzegovina'),
      'BW' => array('value' => '267', 'text' => 'Botswana'),
      'BR' => array('value' => '55', 'text' => 'Brazil'),
      'BN' => array('value' => '673', 'text' => 'Brunei'),
      'BG' => array('value' => '359', 'text' => 'Bulgaria'),
      'BF' => array('value' => '226', 'text' => 'Burkina Faso'),
      'BI' => array('value' => '257', 'text' => 'Burundi'),
      'KH' => array('value' => '855', 'text' => 'Cambodia'),
      'CM' => array('value' => '237', 'text' => 'Cameroon'),
      'CA' => array('value' => '1', 'text' => 'Canada'),
      'CV' => array('value' => '238', 'text' => 'Cape Verde Islands'),
      'KY' => array('value' => '1345', 'text' => 'Cayman Islands'),
      'CF' => array('value' => '236', 'text' => 'Central African Republic'),
      'CL' => array('value' => '56', 'text' => 'Chile'),
      'CN' => array('value' => '86', 'text' => 'China'),
      'CO' => array('value' => '57', 'text' => 'Colombia'),
      'KM' => array('value' => '269', 'text' => 'Comoros'),
      'CG' => array('value' => '242', 'text' => 'Congo'),
      'CK' => array('value' => '682', 'text' => 'Cook Islands'),
      'CR' => array('value' => '506', 'text' => 'Costa Rica'),
      'HR' => array('value' => '385', 'text' => 'Croatia'),
      'CU' => array('value' => '53', 'text' => 'Cuba'),
      'CY' => array('value' => '90392', 'text' => 'Cyprus North'),
      'CY' => array('value' => '357', 'text' => 'Cyprus South'),
      'CZ' => array('value' => '42', 'text' => 'Czech Republic'),
      'DK' => array('value' => '45', 'text' => 'Denmark'),
      'DJ' => array('value' => '253', 'text' => 'Djibouti'),
      'DM' => array('value' => '1809', 'text' => 'Dominica'),
      'DO' => array('value' => '1809', 'text' => 'Dominican Republic'),
      'EC' => array('value' => '593', 'text' => 'Ecuador'),
      'EG' => array('value' => '20', 'text' => 'Egypt'),
      'SV' => array('value' => '503', 'text' => 'El Salvador'),
      'GQ' => array('value' => '240', 'text' => 'Equatorial Guinea'),
      'ER' => array('value' => '291', 'text' => 'Eritrea'),
      'EE' => array('value' => '372', 'text' => 'Estonia'),
      'ET' => array('value' => '251', 'text' => 'Ethiopia'),
      'FK' => array('value' => '500', 'text' => 'Falkland Islands'),
      'FO' => array('value' => '298', 'text' => 'Faroe Islands'),
      'FJ' => array('value' => '679', 'text' => 'Fiji'),
      'FI' => array('value' => '358', 'text' => 'Finland'),
      'FR' => array('value' => '33', 'text' => 'France'),
      'GF' => array('value' => '594', 'text' => 'French Guiana'),
      'PF' => array('value' => '689', 'text' => 'French Polynesia'),
      'GA' => array('value' => '241', 'text' => 'Gabon'),
      'GM' => array('value' => '220', 'text' => 'Gambia'),
      'GE' => array('value' => '7880', 'text' => 'Georgia'),
      'DE' => array('value' => '49', 'text' => 'Germany'),
      'GH' => array('value' => '233', 'text' => 'Ghana'),
      'GI' => array('value' => '350', 'text' => 'Gibraltar'),
      'GR' => array('value' => '30', 'text' => 'Greece'),
      'GL' => array('value' => '299', 'text' => 'Greenland'),
      'GD' => array('value' => '1473', 'text' => 'Grenada'),
      'GP' => array('value' => '590', 'text' => 'Guadeloupe'),
      'GU' => array('value' => '671', 'text' => 'Guam'),
      'GT' => array('value' => '502', 'text' => 'Guatemala'),
      'GN' => array('value' => '224', 'text' => 'Guinea'),
      'GW' => array('value' => '245', 'text' => 'Guinea - Bissau'),
      'GY' => array('value' => '592', 'text' => 'Guyana'),
      'HT' => array('value' => '509', 'text' => 'Haiti'),
      'HN' => array('value' => '504', 'text' => 'Honduras'),
      'HK' => array('value' => '852', 'text' => 'Hong Kong'),
      'HU' => array('value' => '36', 'text' => 'Hungary'),
      'IS' => array('value' => '354', 'text' => 'Iceland'),
      'IN' => array('value' => '91', 'text' => 'India'),
      'ID' => array('value' => '62', 'text' => 'Indonesia'),
      'IR' => array('value' => '98', 'text' => 'Iran'),
      'IQ' => array('value' => '964', 'text' => 'Iraq'),
      'IE' => array('value' => '353', 'text' => 'Ireland'),
      'IL' => array('value' => '972', 'text' => 'Israel'),
      'IT' => array('value' => '39', 'text' => 'Italy'),
      'JM' => array('value' => '1876', 'text' => 'Jamaica'),
      'JP' => array('value' => '81', 'text' => 'Japan'),
      'JO' => array('value' => '962', 'text' => 'Jordan'),
      'KZ' => array('value' => '7', 'text' => 'Kazakhstan'),
      'KE' => array('value' => '254', 'text' => 'Kenya'),
      'KI' => array('value' => '686', 'text' => 'Kiribati'),
      'KP' => array('value' => '850', 'text' => 'Korea North'),
      'KR' => array('value' => '82', 'text' => 'Korea South'),
      'KW' => array('value' => '965', 'text' => 'Kuwait'),
      'KG' => array('value' => '996', 'text' => 'Kyrgyzstan'),
      'LA' => array('value' => '856', 'text' => 'Laos'),
      'LV' => array('value' => '371', 'text' => 'Latvia'),
      'LB' => array('value' => '961', 'text' => 'Lebanon'),
      'LS' => array('value' => '266', 'text' => 'Lesotho'),
      'LR' => array('value' => '231', 'text' => 'Liberia'),
      'LY' => array('value' => '218', 'text' => 'Libya'),
      'LI' => array('value' => '417', 'text' => 'Liechtenstein'),
      'LT' => array('value' => '370', 'text' => 'Lithuania'),
      'LU' => array('value' => '352', 'text' => 'Luxembourg'),
      'MO' => array('value' => '853', 'text' => 'Macao'),
      'MK' => array('value' => '389', 'text' => 'Macedonia'),
      'MG' => array('value' => '261', 'text' => 'Madagascar'),
      'MW' => array('value' => '265', 'text' => 'Malawi'),
      'MY' => array('value' => '60', 'text' => 'Malaysia'),
      'MV' => array('value' => '960', 'text' => 'Maldives'),
      'ML' => array('value' => '223', 'text' => 'Mali'),
      'MT' => array('value' => '356', 'text' => 'Malta'),
      'MH' => array('value' => '692', 'text' => 'Marshall Islands'),
      'MQ' => array('value' => '596', 'text' => 'Martinique'),
      'MR' => array('value' => '222', 'text' => 'Mauritania'),
      'YT' => array('value' => '269', 'text' => 'Mayotte'),
      'MX' => array('value' => '52', 'text' => 'Mexico'),
      'FM' => array('value' => '691', 'text' => 'Micronesia'),
      'MD' => array('value' => '373', 'text' => 'Moldova'),
      'MC' => array('value' => '377', 'text' => 'Monaco'),
      'MN' => array('value' => '976', 'text' => 'Mongolia'),
      'MS' => array('value' => '1664', 'text' => 'Montserrat'),
      'MA' => array('value' => '212', 'text' => 'Morocco'),
      'MZ' => array('value' => '258', 'text' => 'Mozambique'),
      'MN' => array('value' => '95', 'text' => 'Myanmar'),
      'NA' => array('value' => '264', 'text' => 'Namibia'),
      'NR' => array('value' => '674', 'text' => 'Nauru'),
      'NP' => array('value' => '977', 'text' => 'Nepal'),
      'NL' => array('value' => '31', 'text' => 'Netherlands'),
      'NC' => array('value' => '687', 'text' => 'New Caledonia'),
      'NZ' => array('value' => '64', 'text' => 'New Zealand'),
      'NI' => array('value' => '505', 'text' => 'Nicaragua'),
      'NE' => array('value' => '227', 'text' => 'Niger'),
      'NG' => array('value' => '234', 'text' => 'Nigeria'),
      'NU' => array('value' => '683', 'text' => 'Niue'),
      'NF' => array('value' => '672', 'text' => 'Norfolk Islands'),
      'NP' => array('value' => '670', 'text' => 'Northern Marianas'),
      'NO' => array('value' => '47', 'text' => 'Norway'),
      'OM' => array('value' => '968', 'text' => 'Oman'),
      'PW' => array('value' => '680', 'text' => 'Palau'),
      'PA' => array('value' => '507', 'text' => 'Panama'),
      'PG' => array('value' => '675', 'text' => 'Papua New Guinea'),
      'PY' => array('value' => '595', 'text' => 'Paraguay'),
      'PE' => array('value' => '51', 'text' => 'Peru'),
      'PH' => array('value' => '63', 'text' => 'Philippines'),
      'PL' => array('value' => '48', 'text' => 'Poland'),
      'PT' => array('value' => '351', 'text' => 'Portugal'),
      'PR' => array('value' => '1787', 'text' => 'Puerto Rico'),
      'QA' => array('value' => '974', 'text' => 'Qatar'),
      'RE' => array('value' => '262', 'text' => 'Reunion'),
      'RO' => array('value' => '40', 'text' => 'Romania'),
      'RU' => array('value' => '7', 'text' => 'Russia'),
      'RW' => array('value' => '250', 'text' => 'Rwanda'),
      'SM' => array('value' => '378', 'text' => 'San Marino'),
      'ST' => array('value' => '239', 'text' => 'Sao Tome &amp; Principe'),
      'SA' => array('value' => '966', 'text' => 'Saudi Arabia'),
      'SN' => array('value' => '221', 'text' => 'Senegal'),
      'CS' => array('value' => '381', 'text' => 'Serbia'),
      'SC' => array('value' => '248', 'text' => 'Seychelles'),
      'SL' => array('value' => '232', 'text' => 'Sierra Leone'),
      'SG' => array('value' => '65', 'text' => 'Singapore'),
      'SK' => array('value' => '421', 'text' => 'Slovak Republic'),
      'SI' => array('value' => '386', 'text' => 'Slovenia'),
      'SB' => array('value' => '677', 'text' => 'Solomon Islands'),
      'SO' => array('value' => '252', 'text' => 'Somalia'),
      'ZA' => array('value' => '27', 'text' => 'South Africa'),
      'ES' => array('value' => '34', 'text' => 'Spain'),
      'LK' => array('value' => '94', 'text' => 'Sri Lanka'),
      'SH' => array('value' => '290', 'text' => 'St. Helena'),
      'KN' => array('value' => '1869', 'text' => 'St. Kitts'),
      'SC' => array('value' => '1758', 'text' => 'St. Lucia'),
      'SD' => array('value' => '249', 'text' => 'Sudan'),
      'SR' => array('value' => '597', 'text' => 'Suriname'),
      'SZ' => array('value' => '268', 'text' => 'Swaziland'),
      'SE' => array('value' => '46', 'text' => 'Sweden'),
      'CH' => array('value' => '41', 'text' => 'Switzerland'),
      'SI' => array('value' => '963', 'text' => 'Syria'),
      'TW' => array('value' => '886', 'text' => 'Taiwan'),
      'TJ' => array('value' => '7', 'text' => 'Tajikstan'),
      'TH' => array('value' => '66', 'text' => 'Thailand'),
      'TG' => array('value' => '228', 'text' => 'Togo'),
      'TO' => array('value' => '676', 'text' => 'Tonga'),
      'TT' => array('value' => '1868', 'text' => 'Trinidad &amp; Tobago'),
      'TN' => array('value' => '216', 'text' => 'Tunisia'),
      'TR' => array('value' => '90', 'text' => 'Turkey'),
      'TM' => array('value' => '7', 'text' => 'Turkmenistan'),
      'TM' => array('value' => '993', 'text' => 'Turkmenistan'),
      'TC' => array('value' => '1649', 'text' => 'Turks &amp; Caicos Islands'),
      'TV' => array('value' => '688', 'text' => 'Tuvalu'),
      'UG' => array('value' => '256', 'text' => 'Uganda'),
      'GB' => array('value' => '44', 'text' => 'UK'),
      'UA' => array('value' => '380', 'text' => 'Ukraine'),
      'AE' => array('value' => '971', 'text' => 'United Arab Emirates'),
      'UY' => array('value' => '598', 'text' => 'Uruguay'),
      'US' => array('value' => '1', 'text' => 'USA'),
      'UZ' => array('value' => '7', 'text' => 'Uzbekistan'),
      'VU' => array('value' => '678', 'text' => 'Vanuatu'),
      'VA' => array('value' => '379', 'text' => 'Vatican City'),
      'VE' => array('value' => '58', 'text' => 'Venezuela'),
      'VN' => array('value' => '84', 'text' => 'Vietnam'),
      'VG' => array('value' => '84', 'text' => 'Virgin Islands - British'),
      'VI' => array('value' => '84', 'text' => 'Virgin Islands - US'),
      'WF' => array('value' => '681', 'text' => 'Wallis &amp; Futuna'),
      'YE' => array('value' => '969', 'text' => 'Yemen (North)'),
      'YE' => array('value' => '967', 'text' => 'Yemen (South)'),
      'ZM' => array('value' => '260', 'text' => 'Zambia'),
      'ZW' => array('value' => '263', 'text' => 'Zimbabwe'),
    );
  }

}