name: 'Configuration Import - Delete Entities'
type: module
description: 'If a configuration import detects entities that need to be deleted, this module gives the option to automatically delete them.'
package: 'Other'
# core: 8.x
dependencies:
  - config
# Information added by Drupal.org packaging script on 2017-06-13
version: '8.x-1.0-alpha1'
core: '8.x'
project: 'config_import_de'
datestamp: 1497359358
