config_import_de.settings:
  title: 'Config import - delete entities'
  description: 'Configure deletion of entities that prevent importing configurations.'
  route_name: config_import_de.settings
  parent: system.admin_config_development
