config_import_de.settings:
  path: '/admin/config/development/config_import_de'
  defaults:
    _form: '\Drupal\config_import_de\Form\ConfigImportDeSettingsForm'
    _title: 'Config Import - Delete Entities'
  requirements:
    _permission: 'import configuration'