name: dgreat
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: dgreat
  id: 41cad7fe-472d-43a9-a470-d391b9622376
  xdebug: true
services:
 d7db:
   type: mariadb
   creds:
     user: drupal7db
     password: drupal7db
     database: drupal7db
