<?php

/**
 * @file
 * Contains dgreat_modal_webforms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dgreat_modal_webforms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dgreat_modal_webforms module.
    case 'help.page.dgreat_modal_webforms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Expose webforms as blocks that can be used in modals.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dgreat_modal_webforms_theme() {
  return [
    'dgreat_modal_webforms' => [
      'render element' => 'children',
    ],
  ];
}
