<?php

/**
 * @file
 * Contains usf_dashboard.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\Role;

/**
 * Implements hook_help().
 */
function usf_dashboard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the usf_dashboard module.
    case 'help.page.usf_dashboard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Personalized homepage for authenticated users.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function usf_dashboard_theme($existing, $type, $theme, $path) {
  $variables = array(
    'usf_dashboard' => array(
      'variables' => array(
        'dashboard_content' => NULL,
      ),
      'template' => 'usf-dashboard',
    ),
  );
  return $variables;
}


/**
 * Template preprocess function for usf_dashboard.
 *
 * @param array $variables
 *   An associative array containing:
 *   - dashboard_content
 */
function template_preprocess_usf_dashboard(&$variables) {

  // Load the system role objects.
  $role_objects = Role::loadMultiple();
  // Get the current user's id.
  $uid = \Drupal::currentUser()->id();
  $user = \Drupal\user\Entity\User::load($uid);

  // Get a block
  $block = \Drupal\block\Entity\Block::load('poweredbydrupal');
  // Get the events_slider view
  $display_id = 'default';
  $view_name = 'events_featured';
  $events_slider = \Drupal\views\Views::getView($view_name);
  $events_slider->setArguments(array());
  $events_slider->setDisplay($display_id);
  $events_slider->preExecute();
  $events_slider->execute();

  $variables['dashboard_content'] = array(
    "dashboard_user" => $user,
    "system_roles" => $role_objects,
    "my_block" => \Drupal::entityTypeManager()
      ->getViewBuilder('block')
      ->view($block),
    "events_slider" => $events_slider->buildRenderable($display_id)
  );

}
