<?php

/**
 * @file
 * Contains dgreat_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function dgreat_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dgreat_views module.
    case 'help.page.dgreat_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom code related to the views on the site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_pre_render().
 */
function dgreat_views_views_pre_render(ViewExecutable $view) {
  $name = $view->id();
  $display = $view->current_display;

  // Removes the duplicates from the Group Content View.
  switch ($name) {
    case 'favorite_links':
    case 'favorite_links_quick_menu':
      $unique_nids = $new_results = [];
      foreach ($view->result as $index => $result) {
        // Grab the nid from the related node.
        $node = $result->_relationship_entities["gc__node"];
        $nid = $node->id();

        // If it isn;t in there, add it and the result.
        if (!in_array($nid, $unique_nids)) {
          $unique_nids[] = $nid;
          $new_results[] = $result;
        }
      }

      // Set our unique set of results based of of nid.
      $view->result = $new_results;

      break;
  }

}