browser_sync:
  enabled: false
  host: localhost
  port: 3000
clear_registry: false
ie_enabled: false
ie_enabled_versions:
  ie8: false
  ie9: false
_core:
  default_config_hash: ZV9Z7jcEXqz3IwhjCEyMDfl5AOKIFGvf5MieggpR950
