<<<<<<< HEAD:config/block.block.acontactbox.yml
uuid: 8b9b2730-3a21-44a6-9168-270bb738ba40
=======
uuid: 5ac7a70b-876d-4533-a900-bde6698751fc
>>>>>>> master:config/block.block.usfstagescontactbox.yml
langcode: en
status: true
dependencies:
  content:
<<<<<<< HEAD:config/block.block.acontactbox.yml
    - 'block_content:contact:dfe05137-73c9-4bca-a8bd-52693485c591'
=======
    - 'block_content:contact:3066bea9-5a0f-47f6-9f41-cc4e0522e5fc'
>>>>>>> master:config/block.block.usfstagescontactbox.yml
  module:
    - block_content
    - block_visibility_groups
    - system
  theme:
    - myusf
<<<<<<< HEAD:config/block.block.acontactbox.yml
id: acontactbox
theme: myusf
region: sidebar_second
weight: 0
provider: null
plugin: 'block_content:dfe05137-73c9-4bca-a8bd-52693485c591'
settings:
  id: 'block_content:dfe05137-73c9-4bca-a8bd-52693485c591'
  label: 'A Contact Box'
=======
id: usfstagescontactbox
theme: myusf
region: sidebar_second
weight: 32
provider: null
plugin: 'block_content:3066bea9-5a0f-47f6-9f41-cc4e0522e5fc'
settings:
  id: 'block_content:3066bea9-5a0f-47f6-9f41-cc4e0522e5fc'
  label: 'USF STAGES contact box'
>>>>>>> master:config/block.block.usfstagescontactbox.yml
  provider: block_content
  label_display: visible
  status: true
  info: ''
  view_mode: full
visibility:
  condition_group:
    id: condition_group
    negate: false
    block_visibility_group: ''
    context_mapping: {  }
  request_path:
    id: request_path
<<<<<<< HEAD:config/block.block.acontactbox.yml
    pages: "/cediploma\r\n/cediploma/*"
=======
    pages: "/usf-stages\r\n/usf-stages/*"
>>>>>>> master:config/block.block.usfstagescontactbox.yml
    negate: false
    context_mapping: {  }
