fetch:
  frequency: 0
  overwrite: 0
field:
  field_mapping: ''
role:
  role_mapping: ''
  deny_no_match: 0
  deny_registration_no_match: 0
_core:
  default_config_hash: dDe-Mk-tgyxkPBScz5RX6IPvItBUUCQnhpJkQ1q3Y4A
