_core:
  default_config_hash: JUHKHJeHl1bWXY41HMIcDR-VmAWvJ4OJycDubCkIeDU
minimum_single: 15
minimum_multiple: 5
disable_search_threshold: 0
minimum_width: 0
jquery_selector: select
search_contains: false
disable_search: false
allow_single_deselect: false
disabled_themes:
  seven: '0'
  adminimal_theme: '0'
  bootstrap_barrio: '0'
  myusf: '0'
chosen_include: 1
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
