_core:
  default_config_hash: wH40znhdAqFaoXVoSEc3m3byPL7h68yeKKdYtXUi-no
embed_provider: '//noembed.com/embed?url={url}&callback={callback}'
ckeditor_version: ''
plugins_version_installed: 47.6.0
plugins_installed_version: ''
