embed_provider: '//noembed.com/embed?url={url}&callback={callback}'
ckeditor_version: ''
plugins_installed_version: ''
_core:
  default_config_hash: wH40znhdAqFaoXVoSEc3m3byPL7h68yeKKdYtXUi-no
plugins_version_installed: 4.18.0
