ignored_config_entities:
  0: 'block.block.*'
  2: 'system.menu.*'
  4: 'webform.webform.*'
  6: 'sendgrid_integration.*'
  8: 'block_visibility_groups.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
