ignored_config_entities:
  0: 'block.block.*'
  2: 'system.menu.*'
  4: 'webform.webform.webform_*'
  6: 'sendgrid_integration.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
