ignored_config_entities:
  0: 'block.block.*'
  2: 'system.menu.*'
  4: 'webform.webform.*'
  6: ~webform.webform.template_student_survey
  8: 'sendgrid_integration.*'
  10: 'block_visibility_groups.*'
  12: 'simple_block.simple_block.*'
  14: 'migrate_plus.migration.instagram_*'
  16: seckit.settings
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
