_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - 'block.block.*'
  - 'block_visibility_groups.*'
  - 'migrate_plus.migration.instagram_*'
  - seckit.settings
  - 'sendgrid_integration.*'
  - 'simple_block.simple_block.*'
  - 'system.menu.*'
  - 'webform.webform.*'
  - ~webform.webform.template_student_survey
