ignored_config_entities:
  - 'block.block.*'
  - 'system.menu.*'
  - 'webform.webform.*'
  - ~webform.webform.template_student_survey
  - 'sendgrid_integration.*'
  - 'block_visibility_groups.*'
  - 'simple_block.simple_block.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
