_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  automated_cron: 0
  ban: 0
  basic_auth: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_type_templates: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  bootstrap_library: 0
  bootstrap_paragraphs: 0
  bp_webform: 0
  breakpoint: 0
  cas: 0
  cas_attributes: 0
  cediploma: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_media_embed: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_direct_save: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  delete_all: 0
  devel: 0
  dgreat_group: 0
  dgreat_hide_link: 0
  dgreat_nodes: 0
  dgreat_student_surveys: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  easy_install: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  externalauth: 0
  facets: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  file_delete: 0
  filter: 0
  flag: 0
  gnode: 0
  group: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  link_attributes: 0
  linkit: 0
  mailsystem: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  migrate_upgrade: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_after_login: 0
  redis: 0
  rest: 0
  scheduler: 0
  search_api: 0
  search_api_db: 0
  search_api_pantheon: 0
  search_api_solr: 0
  search_api_solr_legacy: 0
  seckit: 0
  sendgrid_integration: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_block: 0
  sitewide_alert: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_import: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  usf_dashboard: 0
  variationcache: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_devel: 0
  webform_image_select: 0
  webform_jqueryui_buttons: 0
  webform_location_geocomplete: 0
  webform_migrate: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_toggles: 0
  webform_ui: 0
  webform_views: 0
  weight: 0
  workbench: 0
  workbench_access: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  xmlsitemap: 1
  dgreat_views: 10
  views: 10
  standard: 1000
theme:
  seven: 0
  adminimal_theme: 0
  bootstrap_barrio: 0
  myusf: 0
profile: standard
