module:
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  bootstrap_library: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dgreat_group: 0
  dgreat_migration: 0
  dgreat_nodes: 0
  dgreat_views: 0
  dynamic_page_cache: 0
  easy_install: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  gnode: 0
  group: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  link: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  migrate_upgrade: 0
  node: 0
  options: 0
  page_cache: 0
  paragraph_migration: 0
  paragraphs: 0
  path: 0
  quickedit: 0
  rdf: 0
  search: 0
  search_api: 0
  search_api_pantheon: 0
  search_api_solr: 0
  shortcut: 0
  simple_block: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  bartik: 0
  bootstrap_barrio: 0
  bootstrap_barrio_subtheme: 0
  bootstrap: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
