unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: true
element_name: Specialty
time_limit: 3
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_announcement_form: false
  node_announcements_list_page_form: false
  node_article_form: false
  node_community_post_form: false
  node_dashboard_form: false
  node_event_form: false
  node_event_search_form: false
  node_faculty_form: false
  node_favorite_link_form: false
  node_instagram_form: false
  node_jobs_list_form: false
  node_news_form: false
  node_page_form: false
  node_private_page_form: false
  node_quick_favs_form: false
  node_share_arbitrary_form: false
  node_share_page_form: false
  node_twitter_form: false
  node_webform_form: false
  comment_comment_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
