abs_urls: false
admin_theme: false
roles_profiles:
  administrator:
    public: admin
    private: admin
  editor:
    public: member
    private: member
  all_access:
    public: all_access_profile
    private: all_access_profile
_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
