abs_urls: false
admin_theme: false
roles_profiles:
  administrator:
    public: admin
    private: admin
  editor:
    public: member
    private: member
_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
