negotiation:
  language_content:
    enabled:
      language-interface: 0
  language_url:
    enabled:
      language-url: 0
      language-url-fallback: 1
configurable:
  - language_interface
all:
  - language_interface
  - language_content
  - language_url
