features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 1
bootstrap_barrio_library: cdn
bootstrap_barrio_fluid_container: 0
bootstrap_barrio_sidebar_position: both
bootstrap_barrio_content_offset: '0'
bootstrap_barrio_sidebar_collapse: 0
bootstrap_barrio_sidebar_first_width: '3'
bootstrap_barrio_sidebar_first_offset: '0'
bootstrap_barrio_sidebar_second_width: '3'
bootstrap_barrio_sidebar_second_offset: '0'
bootstrap_barrio_button_outline: 0
bootstrap_barrio_button_size: ''
bootstrap_barrio_navbar_toggle: navbar-toggleable-md
bootstrap_barrio_navbar_container: 1
bootstrap_barrio_navbar_top_position: ''
bootstrap_barrio_navbar_top_color: inverse
bootstrap_barrio_navbar_top_background: ''
bootstrap_barrio_navbar_position: ''
bootstrap_barrio_navbar_color: ''
bootstrap_barrio_navbar_background: ''
bootstrap_barrio_navbar_top_affix: 0
bootstrap_barrio_navbar_affix: 0
bootstrap_barrio_sidebar_first_affix: 0
bootstrap_barrio_sidebar_second_affix: 0
bootstrap_barrio_scroll_spy: ''
bootstrap_barrio_google_fonts: ''
bootstrap_barrio_icons: ''
bootstrap_barrio_system_messages: ''
