not_found_exception_patterns:
  - "/\\/user\\/.*\\/view/\r"
  - "/.*\\.aspx/\r"
  - "/.*\\.asp/\r"
  - "/.*\\.jsp/\r"
  - "/\\/blog_edit\\.php/\r"
  - "/\\/blogs\\.php/\r"
  - "/\\/wp-admin.*/\r"
  - "/\\/wp-login.*/\r"
  - "/\\/my_blogs/\r"
  - "/\\/system\\/.*\\.php/\r"
  - "/.*systopice.*/\r"
  - "/.*login.json/\r"
  - '/\/episerver.*/'
_core:
  default_config_hash: xRKQpemYizW_6JE8p1XI9VvGW0AANmWsJwrCXlEDixo
