user_never_lastlogin_value: ''
user_never_lastlogin_period: days
user_lastlogin_value: '3'
user_lastlogin_period: month
user_inactive_value: ''
user_inactive_period: days
user_blocked_value: ''
user_blocked_period: days
enabled_never_loggedin_users: 0
enabled_loggedin_users: 1
enabled_inactive_users: 0
enabled_blocked_users: 0
purge_included_users_roles:
  authenticated: authenticated
  administrator: 0
  editor: 0
  faculty: 0
  all_access: 0
  student: 0
  online_student: 0
  admitted_student: 0
  finance: 0
  employee: 0
  prehire_faculty: 0
  prehire_staff: 0
  bi_group: 0
  vcl_staff: 0
  online_intaccept: 0
  service_editor: 0
  som_ug: 0
  som_grad: 0
  as_ug: 0
  as_grad: 0
  sonhp_ug: 0
  sonhp_grad: 0
  law: 0
  soe: 0
  box_editor: 0
  webform_editor: 0
purge_excluded_users_roles:
  administrator: administrator
  editor: 0
  faculty: 0
  all_access: 0
  student: 0
  online_student: 0
  admitted_student: 0
  finance: 0
  employee: 0
  prehire_faculty: 0
  prehire_staff: 0
  bi_group: 0
  vcl_staff: 0
  online_intaccept: 0
  service_editor: 0
  som_ug: 0
  som_grad: 0
  as_ug: 0
  as_grad: 0
  sonhp_ug: 0
  sonhp_grad: 0
  law: 0
  soe: 0
  box_editor: 0
  webform_editor: 0
purge_on_cron: 0
inactive_user_notify_text: "Dear User, \r\n\r\nYour account has been deleted due the website’s policy to automatically remove users who match certain criteria. If you have concerns regarding the deletion, please talk to the administrator of the website. \r\n\r\nThank you"
send_email_notification: 0
purge_user_cancel_method: user_cancel_reassign
disregard_blocked_users: 0
