login_redirection:
  anonymous: null
  authenticated: /dashboard
  administrator: /dashboard
  editor: /dashboard
  faculty: /dashboard
  all_access: /dashboard
  student: /dashboard
  online_student: /dashboard
  admitted_student: /dashboard
  finance: /dashboard
  employee: /dashboard
  prehire_faculty: /dashboard
  prehire_staff: /dashboard
  bi_group: /dashboard
  vcl_staff: /dashboard
  online_intaccept: /dashboard
  service_editor: /dashboard
  som_ug: /dashboard
  som_grad: /dashboard
  as_ug: /dashboard
  as_grad: /dashboard
  sonhp_ug: /dashboard
  sonhp_grad: /dashboard
  law: /dashboard
  soe: /dashboard
  box_editor: /dashboard
  webform_editor: /dashboard
