seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: false
      webkit: false
    report-only: false
    default-src: '''self'''
    script-src: '''self'' ''unsafe-inline'' ''unsafe-eval'' data: *.bootstrapcdn.com *.glia.com *.google.com *.google-analytics.com *.googleapis.com *.googletagmanager.com *.jquery.com *.jquery.js *.newrelic.com *.nr-data.net polyfill.io *.purechat.com *.purechatcdn.com *.salemove.com siteimproveanalytics.com *.syndication.twimg.com *.twitter.com unpkg.com *.usfca.edu'
    object-src: '''self'''
    img-src: '''self'' data: *.google.com *.googleapis.com *.gstatic.com *.usfca.edu *.cdninstagram.com *.google-analytics.com *.googleusercontent.com *.siteimproveanalytics.io *.twimg.com *.twitter.com *.vimeocdn.com *.ytimg.com'
    media-src: '''self'' *.salemove.com'
    frame-src: '''self'' *.app.box.com *.assetworks.com *.e2ma.net *.google.com *.twitter.com *.usfca.edu *.vimeo.com *.youtube.com'
    frame-ancestors: '''self'''
    child-src: '''self'''
    font-src: '''self'' data: *.googleusercontent.com *.googleapis.com *.jquery.com *.bootstrapcdn.com *.gstatic.com'
    connect-src: '''self'' *.glia.com *.google-analytics.com *.nr-data.net *.doubleclick.net *.purechat.com wss://pubsub.salemove.com *.salemove.com *.usfca.edu'
    report-uri: /report-csp-violation
    upgrade-req: true
    policy-uri: ''
    style-src: '''self'' ''unsafe-inline'' *.bootstrapcdn.com chosen.css *.googleapis.com *.google.com *.jquery.com  wss://pubsub.salemove.com *.salemove.com *.twimg.com *.twitter.com'
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 2
seckit_csrf:
  origin: false
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '1'
  x_frame_allow_from: ''
seckit_ssl:
  hsts: true
  hsts_subdomains: true
  hsts_max_age: 1000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: false
  referrer_policy_policy: strict-origin-when-cross-origin
  disable_autocomplete: false
_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
