_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: false
      webkit: false
    report-only: false
    default-src: '''self'''
    script-src: '''self'' ''unsafe-inline'' ''unsafe-eval'' data: *.bootstrapcdn.com *.cloudflare.com *.rawgit.com *.cognitoforms.com *.facebook.net *.glia.com *.google.com *.google-analytics.com *.googleapis.com *.googletagmanager.com *.gstatic.com *.jquery.com *.jquery.js *.jsdelivr.net *.kaspersky-labs.com *.newrelic.com *.nr-data.net polyfill.io *.purechat.com *.purechatcdn.com *.salemove.com siteimproveanalytics.com *.syndication.twimg.com *.tableau.com *.technolutions.net *.twitter.com unpkg.com *.usfca.edu *.bootcss.com *.ssa.gov'
    object-src: '''self'''
    style-src: '''self'' ''unsafe-inline'' *.bootstrapcdn.com *.cloudflare.com chosen.css *.cognitoforms.com *.googleapis.com *.google.com *.jquery.com  *.jsdelivr.net *.kaspersky-labs.com wss://pubsub.salemove.com *.salemove.com *.twimg.com *.twitter.com *.bootcss.com *.ssa.gov *.technolutions.net '
    img-src: '''self'' data: *.b-cdn.net *.google.com *.googleapis.com *.githubusercontent.com *.rawgit.com *.gstatic.com *.usfca.edu *.cdninstagram.com *.google-analytics.com *.googleusercontent.com *.service-now.com *.siteimproveanalytics.io *.tableau.com *.twimg.com *.twitter.com *.vimeocdn.com *.ytimg.com *.jquery.com *.jsdelivr.net *.ssa.gov'
    media-src: '''self'' *.salemove.com'
    frame-src: '''self'' 138.202.175.186 airtable.com *.app.box.com *.assetworks.com bookwhen.com *.cognitoforms.com echo360.org *.e2ma.net *.facebook.com *.google.com *.ibm.com *.jeffersonfreestate.org *.myatlascms.com *.service-now.com *.tableau.com *.tiki-toki.com *.twitter.com *.usfca.edu *.vimeo.com vimeo.com *.youtube.com *.concept3d.com *.panopto.com *.salesforce.com *.service-now.com *.instructuremedia.com *.guidde.com'
    frame-ancestors: '''self'''
    child-src: '''self'' test-usfca.pantheonsite.io'
    font-src: '''self'' data: *.cognitoforms.com *.googleusercontent.com *.googleapis.com *.jquery.com *.bootstrapcdn.com *.gstatic.com'
    connect-src: '''self'' *.cognitoforms.com *.glia.com *.google.com *.google-analytics.com *.nr-data.net *.doubleclick.net *.purechat.com wss://pubsub.salemove.com *.salemove.com *.technolutions.net *.usfca.edu'
    report-uri: /report-csp-violation
    upgrade-req: true
    policy-uri: ''
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 2
seckit_csrf:
  origin: false
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '3'
  x_frame_allow_from: "https://usfca.instructure.com\r\nhttps://test-usfca.pantheonsite.io"
seckit_ssl:
  hsts: true
  hsts_subdomains: true
  hsts_max_age: 1000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: false
  referrer_policy_policy: strict-origin-when-cross-origin
  disable_autocomplete: false
