max_links: 1000
cron_generate: true
cron_generate_interval: 24
remove_duplicates: true
skip_untranslated: false
batch_process_limit: 1000
base_url: ''
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
