_core:
  default_config_hash: GnciVSpJGwXtuBeAb60PIb2f1e3gGcwKpoyRpxgQ3gM
show_on_admin: false
alert_styles: primary|Default
display_order: ascending
refresh_interval: 3600
automatic_refresh: true
cache_max_age: 15
