_core:
  default_config_hash: GnciVSpJGwXtuBeAb60PIb2f1e3gGcwKpoyRpxgQ3gM
show_on_admin: false
alert_styles: primary|Default
show_count: false
display_order: ascending
automatic_refresh: true
refresh_interval: 3600
cache_max_age: 15
server_side_render: false
show_untranslated: false
