<<<<<<< HEAD
uuid: af61b88a-57c2-4ef7-afeb-1c511daf7a70
=======
uuid: bd00ac1e-9257-4659-9957-d7e4b5a2b335
>>>>>>> 2bc62bf30e700b48bff204ad330bf687fbe7d8fe
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: Uk5hyWhkNv7DHmWKBBnOc-W05llRdbXe19rUxCsSt8Y
id: workbench
label: Workbench
description: 'The editorial workbench.'
locked: true
