_core:
  default_config_hash: AyT9s8OUcclfALRE_imByOMgtZ19eOlqdF6zI3p7yqo
langcode: en
uuid: b702edd7-e2e3-4f70-895d-01426979ca1a
name: myUSF
mail: website-donotreply@usfca.edu
slogan: ''
page:
  403: ''
  404: /node/140623
  front: /node/140134
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
