features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://icon_32x32.png'
favicon:
  use_default: 0
  path: 'public://icon_32x32_0.png'
  mimetype: image/png
