message: Hello
langcode: en
year_select: '31556926'
month_select: '0'
day_select: '0'
user_number_select: '100'
user_status: all
user_never_logged_in: 0
user_with_comment: 0
delete_users_on_cron: 1
_core:
  default_config_hash: Llt58xcLanHKBZUHlT10KHCOZogqLUPFPhnn3JHbS7s
preview_button: Preview
submit: 'Save configuration'
form_build_id: form-LO-kXYw1LsThH5af_NtLiCgQAaJWPGK4WTXeBaxxLqk
form_token: crrGf4P5eQXFfIwIvHyKfvu5RB1_sh69WKAE3lqpZes
form_id: Userprune_admin_settings
op: 'Save configuration'
