filter_settings.dgreat_table_header_scope:
  type: mapping
  label: 'Add scope attributes to table headers'
  mapping:
    promote_scoped_cells:
      type: boolean
      label: 'Promote scoped td cells to th'
    normalize_existing:
      type: boolean
      label: 'Normalize existing scope values'
