filter_settings.dgreat_table_header_scope:
  type: mapping
  label: 'Add scope attributes to table headers'
  mapping:
    normalize_existing:
      type: boolean
      label: 'Normalize existing scope values'
