language: php
php:
- 5.6
- 7.1
env:
  matrix:
  - CXX=g++-4.8 TRAVIS_NODE_VERSION="8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- composer self-update
- . $HOME/.nvm/nvm.sh
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- npm install -g npm5
install:
- composer clear-cache
- npm install
- npm run setup
before_script:
- php --version
- composer --version
- node --version
- npm --version
script: npm run ci
notifications:
  email:
    on_success: always
    on_failure: always
  flowdock:
    secure: dE853wBiC+WZkrB1IWks/pALiBu/CjCVgulay9A7ptW2uWuv2Y4Wr+pLcELVUl0AYBMTBc20mwWilDO0nf0vnwBrX7oXkCRkAwlDcNt+u/ZR3dykCaDlUq88+2XBBFLBDGriCI1bZ2eTS14ED7QbfnHf71caYKJjrUa2nXwBGc0=
