<?php

/**
 * @file
 * Provides an address form on the User Account page for Banner.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\UserInterface;
use Drupal\Core\Url;

/**
 * Implements hook_user_login().
 *
 * Checks whether the user needs to update their address, and then prompts them.
 */
function usfb_address_user_login(UserInterface $account) {
  $uid = $account->id();
  $utility = \Drupal::service('usf_utility');

  // Is the Banner address update system enabled?
  if (!\Drupal::state()->get('usfb_address_enabled')) {
    $response = new RedirectResponse($utility->postLoginPath($uid)->toString());
    $response->send();
  }

  // Is today within the admin-defined start and end dates for address updates?
  $start  = \Drupal::state()->get('usfb_address_date_start');
  $end    = \Drupal::state()->get('usfb_address_date_end');
  $today  = \Drupal::time()->getRequestTime();
  if ($today < $start || $today > $end) {
    $response = new RedirectResponse($utility->postLoginPath($uid)->toString());
    $response->send();
  }

  // Is this user a "Student" (rid 6) or "Online Student" (rid 7)?
  if (!$account->hasRole('student') && !$account->hasRole('online_student')) {
    $response = new RedirectResponse($utility->postLoginPath($uid)->toString());
    $response->send();
  }

  // Has the student confirmed or updated their address since the start date?
  $date = $account->get('field_usfb_address_date')->getValue();
  if (isset($date[0]['value'])) {
    if ($date[0]['value'] >= $start) {
      $response = new RedirectResponse($utility->postLoginPath($uid)->toString());
      $response->send();
    }
  }

  // Set that the USFB Address Check still needs to happen.
  $session = \Drupal::request()->getSession();
  if ($session === NULL) {
    $response = new RedirectResponse($utility->postLoginPath($uid)->toString());
    $response->send();
  }
  $session->set('usfb_address_check', TRUE);

  // All validations have passed so far; redirect to the address check form.
  $url = Url::fromUri("internal:/user/{$uid}/edit/address/check");
  $response = new RedirectResponse($url->toString());
  $response->send();
}
