<?php

// Proxy to vendor/autoload_runtime.php generated by symfony/runtime.
// Required because index.php uses a bare require_once 'autoload_runtime.php'
// which resolves relative to the web root, while symfony/runtime places the
// generated file one level up in vendor/.
return require dirname(__DIR__) . '/vendor/autoload_runtime.php';
